CREATE TABLE protectora (
    protectora_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cif VARCHAR2(50) UNIQUE,
    nombre VARCHAR2(100),
    telefono VARCHAR2(255) NOT NULL,
    correo_electronico VARCHAR2(255),
    localidad VARCHAR2(100),
    provincia VARCHAR2(100),
    pais VARCHAR2(100),
    tipo_via VARCHAR2(100),
    nombre_via VARCHAR2(100),
    codigo_postal VARCHAR2(10),
    fecha_alta DATE,
    fecha_modificacion DATE
);

CREATE TABLE redes_sociales (
    id_protectora NUMBER PRIMARY KEY,
    info_red VARCHAR2(255),
    CONSTRAINT fk_protectora_id FOREIGN KEY (id_protectora)
        REFERENCES protectora(protectora_id)
);

CREATE TABLE cliente (
    cliente_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    apellido1 VARCHAR2(100),
    apellido2 VARCHAR2(100),
    fecha_nacimiento DATE,
    telefono VARCHAR2(20),
    correo_electronico VARCHAR2(255),
    codigo_postal VARCHAR2(10),
    localidad VARCHAR2(100),
    provincia VARCHAR2(100),
    pais VARCHAR2(100),
    tipo_via VARCHAR2(100),
    nombre_via VARCHAR2(100),
    fecha_alta DATE,
    fecha_modificacion DATE
);

CREATE TABLE usuario_cliente (
    id_usuario_cliente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_usuario_cliente VARCHAR2(100),
    contrasena_cliente VARCHAR2(100),
    correo_electronico_cliente VARCHAR2(100),
    id_protectora NUMBER, 
    cliente_id NUMBER,
    CONSTRAINT fk_usuario_protectora_id FOREIGN KEY (id_protectora)
        REFERENCES protectora(protectora_id),
    CONSTRAINT fk_usuario_cliente_id FOREIGN KEY (cliente_id)
        REFERENCES cliente(cliente_id)
        ON DELETE CASCADE
);

CREATE TABLE usuario_protectora (
    id_usuario_protectora NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_usuario_protectora VARCHAR2(100),
    contrasena_protectora VARCHAR2(100),
    correo_electronico_protectora VARCHAR2(100),
    protectora_id NUMBER,
    CONSTRAINT fk_up_protectora FOREIGN KEY (protectora_id)
        REFERENCES protectora(protectora_id)
        ON DELETE CASCADE
);


CREATE TABLE raza (
id_raza NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    fecha_alta DATE,
    fecha_modificacion DATE
);

CREATE TABLE patologia (
    id_patologia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    
    fecha_alta DATE,
    fecha_modificacion DATE
);

CREATE TABLE perro (
    perro_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    foto VARCHAR2(255),
    fecha_nacimiento DATE,
    raza NUMBER,
    sexo VARCHAR2(10),
    adoptado VARCHAR2(2) DEFAULT 'No',
    protectora_id NUMBER,
    fecha_alta DATE,
    fecha_modificacion DATE,
    
    CONSTRAINT fk_perro_protectora FOREIGN KEY (protectora_id)
        REFERENCES protectora(protectora_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_perro_raza FOREIGN KEY (raza)
        REFERENCES raza(id_raza)
        
);

CREATE TABLE perro_patologia (
    id_perro_patologia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    perro_id NUMBER,
    id_patologia NUMBER,
    descripcion_pat VARCHAR2(255),
    
    fecha_alta DATE,
    fecha_modificacion DATE,
    
    CONSTRAINT fk_pp_perro FOREIGN KEY (perro_id)
        REFERENCES perro(perro_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pp_patologia FOREIGN KEY (id_patologia)
        REFERENCES patologia(id_patologia)
        
);

CREATE TABLE solicitud_adopcion (
    id_solicitud NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    donacion NUMBER(10,2),
    estado VARCHAR2(50),
    perro_id NUMBER,
    cliente_id NUMBER,
    fecha_alta DATE,
    fecha_modificacion DATE,
    
    CONSTRAINT fk_solicitud_perro FOREIGN KEY (perro_id)
        REFERENCES perro(perro_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_solicitud_cliente FOREIGN KEY (cliente_id)
        REFERENCES cliente(cliente_id)
        ON DELETE CASCADE
        
);

CREATE TABLE cita (
    id_cita NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    donacion NUMBER(10,2),
    estado VARCHAR2(50) DEFAULT 'pendiente',
    fecha_cita DATE,
    cliente_id NUMBER,
    fecha_alta DATE,
    fecha_modificacion DATE,
    
    CONSTRAINT fk_cita_cliente FOREIGN KEY (cliente_id)
        REFERENCES cliente(cliente_id)
        ON DELETE CASCADE
);

CREATE TABLE notificaciones (
    id_notificacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nueva_cita VARCHAR2(5),
    cancelar_cita VARCHAR2(5),
    nueva_adopcion VARCHAR2(5),
    cambio_solicitud VARCHAR2(5),
    protectora_id NUMBER,
    cliente_id NUMBER,
    fecha_alta DATE,
    fecha_modificacion DATE,
    
    CONSTRAINT fk_notif_protectora FOREIGN KEY (protectora_id)
        REFERENCES protectora(protectora_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notif_cliente FOREIGN KEY (cliente_id)
        REFERENCES cliente(cliente_id)
        ON DELETE CASCADE

);


-- Protectora 1
INSERT INTO protectora (cif, nombre, telefono, correo_electronico, localidad, provincia, pais, tipo_via, nombre_via, codigo_postal, fecha_alta, fecha_modificacion)
VALUES ('G12345678', 'Patitas Felices', '912345678', 'info@patitasfelices.org', 'Madrid', 'Madrid', 'España', 'Calle', 'Gran Vía', '28013', SYSDATE, SYSDATE);

-- Protectora 2
INSERT INTO protectora (cif, nombre, telefono, correo_electronico, localidad, provincia, pais, tipo_via, nombre_via, codigo_postal, fecha_alta, fecha_modificacion)
VALUES ('B87654321', 'Amigos Peludos', '934567890', 'contacto@amigospeludos.org', 'Barcelona', 'Barcelona', 'España', 'Avenida', 'Diagonal', '08028', SYSDATE, SYSDATE);



INSERT INTO redes_sociales (id_protectora, redes_sociales)
VALUES (1, 'Facebook: PatitasFelicesMadrid, Instagram: @PatitasFelices');

INSERT INTO redes_sociales (id_protectora, redes_sociales)
VALUES (2, 'Twitter: @AmigosPeludosBCN, Instagram: @AmigosPeludosBarcelona');


-- Cliente 1
INSERT INTO cliente (nombre, apellido1, apellido2, fecha_nacimiento, telefono, correo_electronico, codigo_postal, localidad, provincia, pais, tipo_via, nombre_via, fecha_alta, fecha_modificacion)
VALUES ('María', 'García', 'López', TO_DATE('15/05/1985', 'DD/MM/YYYY'), '600111222', 'maria.garcia@email.com', '28001', 'Madrid', 'Madrid', 'España', 'Calle', 'Alcalá', SYSDATE, SYSDATE);

-- Cliente 2
INSERT INTO cliente (nombre, apellido1, apellido2, fecha_nacimiento, telefono, correo_electronico, codigo_postal, localidad, provincia, pais, tipo_via, nombre_via, fecha_alta, fecha_modificacion)
VALUES ('Juan', 'Martínez', 'Sánchez', TO_DATE('22/10/1990', 'DD/MM/YYYY'), '699888777', 'juan.martinez@email.com', '08015', 'Barcelona', 'Barcelona', 'España', 'Calle', 'Mallorca', SYSDATE, SYSDATE);


-- Usuario para protectora
INSERT INTO usuario (nombre_usuario, contrasena, correo_electronico, id_protectora, cliente_id)
VALUES ('patitas_admin', 'admin123', 'admin@patitasfelices.org', 1, NULL);

-- Usuario para cliente
INSERT INTO usuario (nombre_usuario, contrasena, correo_electronico, id_protectora, cliente_id)
VALUES ('maria85', 'mypassword', 'maria.garcia@email.com', NULL, 1);



INSERT INTO raza (nombre, fecha_alta, fecha_modificacion)
VALUES ('Labrador Retriever', SYSDATE, SYSDATE);

INSERT INTO raza (nombre, fecha_alta, fecha_modificacion)
VALUES ('Pastor Alemán', SYSDATE, SYSDATE);

INSERT INTO raza (nombre, fecha_alta, fecha_modificacion)
VALUES ('Chihuahua', SYSDATE, SYSDATE);


INSERT INTO patologia (nombre, fecha_alta, fecha_modificacion)
VALUES ('Alergia alimentaria', SYSDATE, SYSDATE);

INSERT INTO patologia (nombre, fecha_alta, fecha_modificacion)
VALUES ('Displasia de cadera', SYSDATE, SYSDATE);


-- Perro 1
INSERT INTO perro (nombre, foto, fecha_nacimiento, raza, sexo, adoptado, protectora_id, fecha_alta, fecha_modificacion)
VALUES ('Luna', 'luna.jpg', TO_DATE('10/03/2020', 'DD/MM/YYYY'), 1, 'Hembra', 'No', 1, SYSDATE, SYSDATE);

-- Perro 2
INSERT INTO perro (nombre, foto, fecha_nacimiento, raza, sexo, adoptado, protectora_id, fecha_alta, fecha_modificacion)
VALUES ('Thor', 'thor.jpg', TO_DATE('15/07/2019', 'DD/MM/YYYY'), 2, 'Macho', 'No', 2, SYSDATE, SYSDATE);




INSERT INTO perro_patologia (perro_id, id_patologia, descripcion_pat, fecha_alta, fecha_modificacion)
VALUES (1, 1, 'Alergia al pollo, requiere dieta especial', SYSDATE, SYSDATE);

INSERT INTO perro_patologia (perro_id, id_patologia, descripcion_pat, fecha_alta, fecha_modificacion)
VALUES (2, 2, 'Displasia leve, requiere ejercicio controlado', SYSDATE, SYSDATE);



INSERT INTO solicitud_adopcion (donacion, estado, perro_id, cliente_id, fecha_alta, fecha_modificacion)
VALUES (50.00, 'Pendiente', 1, 1, SYSDATE, SYSDATE);

INSERT INTO solicitud_adopcion (donacion, estado, perro_id, cliente_id, fecha_alta, fecha_modificacion)
VALUES (75.00, 'Aprobada', 2, 2, SYSDATE, SYSDATE);


INSERT INTO cita (donacion, estado, fecha_cita, cliente_id, fecha_alta, fecha_modificacion)
VALUES (20.00, 'pendiente', TO_DATE('25/04/2025', 'DD/MM/YYYY'), 1, SYSDATE, SYSDATE);

INSERT INTO cita (donacion, estado, fecha_cita, cliente_id, fecha_alta, fecha_modificacion)
VALUES (30.00, 'confirmada', TO_DATE('30/04/2025', 'DD/MM/YYYY'), 2, SYSDATE, SYSDATE);


INSERT INTO notificaciones (nueva_cita, cancelar_cita, nueva_adopcion, cambio_solicitud, protectora_id, cliente_id, fecha_alta, fecha_modificacion)
VALUES ('Si', 'No', 'No', 'No', 1, 1, SYSDATE, SYSDATE);

INSERT INTO notificaciones (nueva_cita, cancelar_cita, nueva_adopcion, cambio_solicitud, protectora_id, cliente_id, fecha_alta, fecha_modificacion)
VALUES ('No', 'No', 'Si', 'No', 2, 2, SYSDATE, SYSDATE);






SELECT c.donacion, c.estado, c.fecha_cita, cli.nombre, cli.apellido1, cli.apellido2, cli.correo_electronico AS correo_cliente,
       u.correo_electronico_cliente AS correo_usuario, p.nombre AS nombre_perro 
FROM cita c 
JOIN cliente cli ON c.cliente_id = cli.cliente_id 
LEFT JOIN usuario_cliente u ON cli.cliente_id = u.cliente_id 
LEFT JOIN solicitud_adopcion sa ON sa.cliente_id = cli.cliente_id 
LEFT JOIN perro p ON sa.perro_id = p.perro_id;
